import json
import hashlib

from utils import collect_docs


def main():
    docs, authors, tags = collect_docs()

    payload = {
        "filters": {
            "author": authors,
            "tag": tags,
        },
        "docs": docs,
    }

    content_hash = hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()

    output = {
        "_comment": "DO NOT TOUCH THIS FILE. Auto-generated by utils/docs/build_index.py",
        "timestamp": int(content_hash[:12], 16),
        **payload,
    }

    with open("docs/data.json", "w", encoding="utf-8") as f:
        json.dump(output, f, indent=4)

    print("[=== indexed successfully ===]")


if __name__ == "__main__":
    main()
